### ISSUE TITLE
'Undefined offset: 0'

### ISSUE THREAD

**Issue by dave-miller** [jotafurtado/geocode#2]
Occasionally I get this error message 

``` php
 exception 'ErrorException' with message 'Undefined offset: 0'
```

There is an issue with making the geocode request and there isn't a check for errors such as "ZERO_RESULTS" or "OVER_QUERY_LIMIT".  I have altered my code a bit but believe I have a solution to this issue if your interested.

**Comment by jotafurtado** [comment]
Could you please make a PR?
